form_project/urls.py
from django.contrib import admin
from django.urls import path

import form_example.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('form-example/', form_example.views.form_example)
]

form_example/models.py
from django.db import models

# Create your models here.

form_example/forms.py
from django.core.validators import ValidationError
from django import forms


RADIO_CHOICES = (
    ("Value One", "Value One Display"),
    ("Value Two", "Text For Value Two"),
    ("Value Three", "Value Three's Display Text")
)

BOOK_CHOICES = (
    (
        "Non-Fiction", (
           ("1", "Deep Learning with Keras"),
           ("2", "Web Development with Django")
        )
    ),
    (
        "Fiction", (
           ("3", "Brave New World"),
           ("4", "The Great Gatsby")
        )
    )
)

def validate_email_domain(value):
    if value.split("@")[-1].lower() != "example.com":
        raise ValidationError("The email address must be on the domain example.com.")


class ExampleForm(forms.Form):
    text_input = forms.CharField(max_length=3)
    password_input = forms.CharField(min_length=8, widget=forms.PasswordInput)
    checkbox_on = forms.BooleanField()
    radio_input = forms.ChoiceField(choices=RADIO_CHOICES, widget=forms.RadioSelect)
    favorite_book = forms.ChoiceField(choices=BOOK_CHOICES)
    books_you_own = forms.MultipleChoiceField(required=False, choices=BOOK_CHOICES)
    text_area = forms.CharField(widget=forms.Textarea)
    integer_input = forms.IntegerField(min_value=1, max_value=10)
    float_input = forms.FloatField()
    decimal_input = forms.DecimalField(max_digits=5, decimal_places=3)
    email_input = forms.EmailInput()
    date_input = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))
    hidden_input = forms.CharField(widget=forms.HiddenInput, initial="Hidden Value")

class OrderForm(forms.Form):
    magazine_count = forms.IntegerField(min_value=0, max_value=80,
                                        widget=forms.NumberInput(attrs={"placeholder": "Number of Magazines"}))
    book_count = forms.IntegerField(min_value=0, max_value=50,
                                    widget=forms.NumberInput(attrs={"placeholder": "Number of Books"}))
    send_confirmation = forms.BooleanField(required=False)
    email = forms.EmailField(required=False, validators=[validate_email_domain],
                             widget=forms.EmailInput(attrs={"placeholder": "Your company email address"}))

    def clean_email(self):
        return self.cleaned_data["email"].lower()

    def clean(self):
        clean_data = super().clean()
        if clean_data["send_confirmation"] and not clean_data.get("email"):
           self.add_error("email", "Please enter an email address to receive the confirmation message.")
        elif clean_data.get("email") and not clean_data["send_confirmation"]:
           self.add_error("send_confirmation", "Please check this if you want to receive a confirmation email.")

        item_total = clean_data.get("magazine_count", 0) + clean_data.get("book_count", 0)
        if item_total > 100:
            self.add_error(None, "The total number of items must be 100 or less.")


class NewsletterSignupForm(forms.Form):
    signup = forms.BooleanField(label="Sign up to newsletter?", required=False)
    email = forms.EmailField(help_text="Enter your email address to subscribe", required=False)

    def clean(self):
        cleaned_data = super().clean()

        if cleaned_data["signup"] and not cleaned_data.get("email"):
            self.add_error("email", "Your email address is required if signing up for the newsletter.")

form_example/views.py
from django.shortcuts import render
from .forms import ExampleForm, OrderForm

def form_example(request):
    initial = {"email": "user@example.com"}

    if request.method == "POST":
        #form = ExampleForm(request.POST)
        form = OrderForm(request.POST, initial=initial)

        if form.is_valid():
           for name, value in form.cleaned_data.items():
               print("{}: ({}) {}".format(name, type(value), value))
    else:
        form = OrderForm(initial=initial)

    return render(request=request, template_name="form-example.html",
                  context={"method": request.method, "form": form})

form_example/templates/form-example.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h4>Method : {{ method }}</h4>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p>
            <input type="submit" name="submit_input" value="Submit Input">
        </p>
        <p>
            <button type="submit" name="button_element" value="Button Element">
                Button With <strong>Styled</strong> Text
            </button>
        </p>
    </form>
</body>
</html>

form_example/templates/form-example_org.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h4>Method : {{ method }}</h4>
    <form method="post">
        {% csrf_token %}
        <p>
            <label for="id_text_input">Text Input</label><br>
            <input id="id_text_input" type="text" name="text_input" value="" placeholder="Enter some text">
        </p>
        <p>
            <label for="id_password_input">Password Input</label><br>
            <input id="id_password_input" type="password" name="password_input" value="" placeholder="Your password">
        </p>
        <p>
            <input id="id_checkbox_input" type="checkbox" name="checkbox_on" value="Checkbox Checked" checked>
            <label for="id_checkbox_input">Checkbox</label>
        </p>
        <p>
            <input id="id_radio_one_input" type="radio" name="radio_input" value="Value One">
            <label for="id_radio_one_input">Value One</label>
            <input id="id_radio_two_input" type="radio" name="radio_input" value="Value Two" checked>
            <label for="id_radio_two_input">Value Two</label>
            <input id="id_radio_three_input" type="radio" name="radio_input" value="Value Three">
            <label for="id_radio_three_input">Value Three</label>
        </p>
        <p>
            <label for="id_favorite_book">Favorite Book</label><br>
            <select id="id_favorite_book" name="favorite_book">
                <optgroup label="Non-Fiction">
                    <option value="1">Deep Learning with Keras</option>
                    <option value="2">Web Development with Django</option>
                </optgroup>
                <optgroup label="Fiction">
                    <option value="3">Brave New World</option>
                    <option value="4">The Great Gatsby</option>
                </optgroup>
            </select>
        </p>
        <p>
            <label for="id_books_you_own">Books You Own</label><br>
            <select id="id_books_you_own" name="books_you_own" multiple>
                <optgroup label="Non-Fiction">
                    <option value="1">Deep Learning with Keras</option>
                    <option value="2">Web Development with Django</option>
                </optgroup>
                <optgroup label="Fiction">
                    <option value="3">Brave New World</option>
                    <option value="4">The Great Gatsby</option>
                </optgroup>
            </select>
        </p>
        <p>
            <label for="id_text_area">Text Area</label><br>
            <textarea name="text_area" id="id_text_area" placeholder="Enter multiple lines of text"></textarea>
        </p>
        <p>
             <label for="id_number_input">Number Input</label><br>
             <input id="id_number_input" type="number" name="number_input" value="" step="any" placeholder="A number">
        </p>
        <p>
             <label for="id_email_input">Email Input</label><br>
             <input id="id_email_input" type="email" name="email_input" value="" placeholder="Your email address">
        </p>
        <p>
             <label for="id_date_input">Date Input</label><br>
             <input id="id_date_input" type="date" name="date_input" value="2019-11-23">
        </p>
        <p>
            <input type="submit" name="submit_input" value="Submit Input">
        </p>
        <p>
         <button type="submit" name="button_element" value="Button Element">Button With<strong>Styled</strong>Text
         </button>
        </p>
        <input type="hidden" name="hidden_input" value="Hidden Value">
    </form>
</body>
</html>